apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rs2ex0kon-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/rs2ex0kon-dotnet-basic